name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

     # Pull LFS files only if they are needed in this job
    - name: Git LFS Pull
      run: git lfs pull

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

   # - name: Lint with flake8
   #   run: |
   #     flake8 src/ tests/  # Adjust paths as needed
   
   # Add the model training step
    - name: Train the Model
      run: python src/main.py

   # Add the model uploading step
    - name: Upload Trained Model
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: trained_model.joblib

    - name: Run Tests
      run: |
        pytest tests/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && needs.build-and-test.result == 'success'
    
    steps:
    - uses: actions/checkout@v2

    # Add the LFS pull step here only if your Docker build requires LFS files
    - name: Git LFS Pull
      run: git lfs pull

    - name: Build and Push Docker Image
      run: |
        docker build -t jawadarnob97/predictive-maintenance:latest .
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push jawadarnob97/predictive-maintenance:latest